services:
  - type: web
    name: merobazar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn merobazar.wsgi:application
    postDeployCommand: |
      python manage.py migrate --run-syncdb --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
