# Generated by Django 5.1.7 on 2025-08-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
