# Generated by Django 5.1.7 on 2025-08-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
