# Generated by Django 5.1.7 on 2025-08-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orderitem_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
